// Generated by https://quicktype.io
export interface BackendRegisterUserResponse {
  ok: boolean;
  msg: string;
  usuario: User;
  token: string;
  expiresIn: number;
}

export interface User {
  uid: string;
  name: string;
  token: string;
  expiresIn: number;
}
